### ISSUE TITLE
X Mode

### ISSUE THREAD

**Issue by willitcode** [frc937/swerving-learning-box#1]
Let's implement an "X Mode" button on the controller to make the robot stay still on the field.

**Comment by willitcode** [comment]
The method for this is `SwerveDrive.lockPose()`.

**Comment by Berdenson** [comment]
goin x games mode

**Comment by Berdenson** [comment]
i closed it idk how

**Comment by Berdenson** [comment]
fixed it

**Comment by Berdenson** [comment]
anyways- x games mode
